- name: baselinux
  hosts: all
  roles:
    - baselinux
- name: puppetclients
  hosts: puppetclinets
  roles:
    - puppetclients
- name: puppetmasters
  hosts: puppetmasters
  roles:
    - puppetmasters